##############################################
#            Server Configuration            #
##############################################
server:
  port: 4900
  error:
    include-message: always

##############################################
#           Database Configuration           #
##############################################

spring:
  mvc:
    log-request-details: true
  datasource:
    url: jdbc:h2:mem:salesdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        ddl-auto: none

    # Hibernate ddl auto (create, create-drop, validate, update)

  ##############################################
  #           Security Configuration           #
  ##############################################

  security:
    user:
      name: Admin
      password: pro145$dv
  #    headers:
  #          frame: origin

  ##############################################
  #           Misc Configuration           #
  ##############################################

  session:
    store-type: none
    #     jdbc

    jdbc:
      initialize-schema: always
#      schema:
#        classpath: org/springframework/session/jdbc/sales_db.sql
#      timeout:
#      seconds: 600

    output:
    ansi:
      enabled: DETECT