##############################################
#      Spring Profile Configuration          #
##############################################
spring:
  profiles:
    active: prod
  jpa:
    properties:
#

logging:
  level:
    web: DEBUG          #for additional information

springdoc:
  api-docs:
    path: /api-docs
    title: API Documentation
    description: API Documentation

  swagger-ui:
    path: /swagger-ui
    operationsSorter: method


